### ISSUE TITLE
Paper addition 

### ISSUE THREAD

**Issue by ashok-arjun** [tata1661/FewShotPapers#9]
Hi! 

Thanks for creating this awesome repo!

Would this paper by chance fit in this repo:

Multi-level Semantic Feature Augmentation for One-shot Learning [[paper](https://arxiv.org/abs/1804.05298)] [[code](https://github.com/tankche1/Semantic-Feature-Augmentation-in-Few-shot-Learning)]

**Comment by tata1661** [comment]
Thanks for reminding us! We will include it in the next update.

**Comment by tata1661** [comment]
Added.
